### ISSUE TITLE
api documentation - starting

### ISSUE THREAD

**Issue by bskade** [treolabs/treopim#349]
Hello,
today I tried tropim api. Endpoint documentation looks awesome. However, I do miss a basic tutorial or a how to start. Could not find any information how to get a auth token. Basic Auth is working but I don't think its best practice.

**Comment by rratsun** [comment]
Hello,
It's better to use auth token instead of password when you work with api. In this case you will need to provide username and password/token in `Espo-Authorization` header.
```
"Espo-Authorization: " + base64Encode(username  + ':' + passwordOrToken)
```

1. Obtain an access token by `GET App/user` request with the username and password passed in `Espo-Authorization` header.
2. Use this token instead of password in `Espo-Authorization` header for all further request.
3. If the request returns 401 error that means either username/password is wrong or token is not valid anymore.
